// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdRbxqlUiE9EuGLMs7r-jE1S_YI-FBGms',
    appId: '1:672952437981:web:b78b22f387e80c71a89f34',
    messagingSenderId: '672952437981',
    projectId: 'hojas-terreno',
    authDomain: 'hojas-terreno.firebaseapp.com',
    storageBucket: 'hojas-terreno.firebasestorage.app',
    measurementId: 'G-3J6D986QP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtvbNhmoIy-Y5Omf0KQPsp9hlLXEuScCY',
    appId: '1:672952437981:android:a4805355b1eea8e9a89f34',
    messagingSenderId: '672952437981',
    projectId: 'hojas-terreno',
    storageBucket: 'hojas-terreno.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdRbxqlUiE9EuGLMs7r-jE1S_YI-FBGms',
    appId: '1:672952437981:web:44bfd241252635c6a89f34',
    messagingSenderId: '672952437981',
    projectId: 'hojas-terreno',
    authDomain: 'hojas-terreno.firebaseapp.com',
    storageBucket: 'hojas-terreno.firebasestorage.app',
    measurementId: 'G-N11Q3Q7G3V',
  );
}
